# Use Node.js base image
FROM node:18

# Set working directory in container
WORKDIR /app

# Copy package.json and install dependencies
COPY server/package.json ./
RUN npm install

# Copy rest of the backend files
COPY server .

# Expose port & run server
EXPOSE 5001
CMD ["node", "server.js"]