# Use Node.js base image
FROM node:18

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY client/package.json ./
RUN npm install

# Copy React app files
COPY client .

# Build React app
RUN npm run build

# Expose frontend port
EXPOSE 5173
CMD ["npm", "run", "dev"]